### PR TITLE
feature: introduce "no build" mode

### PR DESCRIPTION
**Pull request by ryangjchandler**
The goal for this pull request and update is to remove the need to manually build PXP files. Right now, you need to use the `pxp build` command to transpile PHP and PXP files ahead of time.

My main problem with this setup is that it adds yet another build step to your project. The majority of us already have build steps for front-end assets and actively try to simplify these processes. With the changes in this PR, it would remove the build step altogether and "just work" out of the box.

There are a couple of caveats with a setup like this which I'll describe.

**1. PXP can only be used on autoloaded files.**

With a build step in place, it was possible for you to write a single `.pxp` file, transpile it and then execute it with PHP. The no-build mode that we have in place now will remove the ability to do that since it hooks into PHP's autoloading mechanism to transpile files on the fly (with a file cache).

I would eventually like to allow using PXP in files that are included/required using the `include` and `require` statements too, but that will require a bit of extra work since Composer's standard autoloader can only autoload .php and .hh (lol) files. That will essentially allow you to use PXP inside of Blade templates, etc.

**2. It adds some overhead to the initial request**

Since the "no build" mode removes that build step, it means that each PXP file being executed needs to be transpiled before it can be used. 

I have added a rudimentary file cache system so that it will only do the transpilation once and will re-transpile if the contents of the file change (using `md5_file()` to generate a hash).

**3. It limits what PXP can do**

The website for PXP shows some examples of what I had in mind for PHP. Introducing things like operator overloading, type aliases and more.

Using a "no build" mode limits what we can introduce into the language since a lot of those features rely on full project analysis. Take type aliases for example. If you defined a type alias in one file and wanted to use it in another, there's no way for PXP to handle that efficiently at runtime.

It would be possible to perform this project analysis at runtime, but would likely have a negative impact on local development speed since it would need to happen each time a PXP file changes.

Production usage would only take a performance hit on the initial transpilation step. That could be removed / reduced a little bit by introducing a `pxp cache` command that you could run on deployment to warm up the PXP cache, similar to how Laravel has a `php artisan view:cache` command that pre-compiles Blade files to reduce runtime overhead.

**Sign off**

I'm going to leave this PR as a draft while I continue to work on some stuff (source maps mainly) but I'd appreciate feedback and thoughts on some of the things I mentioned above, as well as the questions below:

1. Is a "no build" mode truly better?
2. Would you care if there was an overhead on local development requests?
3. Would you be happy to use a `cache` command or similar on deployment to allow PXP to follow it's original development plans?
4. What if PXP didn't use a custom file extension at all and instead went down the `declare()` route? This would allow it to use Composer's built in autoloader. (I don't like the idea since it's then a bit harder to tell what is PXP and what's not)

### CODE REVIEW

**Comment by Larsklopstra** [comment]
I’d just keep the build step honestly

**Comment by assertchris** [comment]
Another option is to make the `pxp cache` command run automatically on `composer du -o`, like I did for pre. That's typically run on prod where you'd want the faster runtime and wouldn't mind the slower build time.

**Comment by ryangjchandler** [comment]
Yes, the Composer plugin would come with the command.

The watch command is an interesting idea too, but it's still a build step. I'll have a okay, @assertchris. Thanks.

**Comment by khalyomede** [comment]
Hi, I follow the project from far, wanted to give you a shout out and congrats!

As a founder, I know you have to limit your focus on the first launch. If releasing this no build mode implies more work because as you highlighted this mode would be limited and people would ultimately ask you why, then I would rather not release this feature at first.

PXP promise is sufficient enough to consider this tool in build only at first. I am sure people looking for PXP have an already solid PHP background, and are looking for a more type-safe way to write their PHP app.

On the other hand, I think this feature would be a great one in the long run. The first similar tool that comes into my mind is `dotnet fsi` which allows to interpret F# code on the fly without having to build it first. I think PXP would definitely benefit from this to improve the developer experience.

Short: not now to let you focus on actual release, great later with adoption

**Comment by ryangjchandler** [comment]
Thanks for the feedback @khalyomede, appreciate it!

**Pull request closed without merging**
